[package]
name = "rusty-edit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.44.0"
imgui = "0.8.0"
imgui-opengl-renderer = "0.11.1"
glium = "0.31.0"